### ISSUE TITLE
calc_oxygen is super broken

### ISSUE THREAD

**Issue by callumrollo** [GliderToolsCommunity/GliderTools#112]
**Describe the bug**
calc_oxygen throws the following error:

>    ll, ul = outlier_bounds_iqr(Y, multiplier=1.5)
ValueError: too many values to unpack (expected 2)

This is an issue with calc_oxygen or outlier_bounds_qr. The latter returns a single masked array while the former expects two objects. I assume the behaviour of one of them changed at some point in the past

**To Reproduce**
calc_oxygen(oxygen, pressure, salinity, temperature)

**Expected behavior**
Not to throw an error :/

**Additional context**
I'm out of my oxygen depth here, but pretty sure this should not happen.

**Comment by callumrollo** [comment]
Further work:

I had a poke at where outlier_bounds_iqr is called. It looks to me like, inplace of the current 

`ll, ul = outlier_bounds_iqr(Y, multiplier=1.5)`

We should have 
```
iqr = outlier_bounds_iqr(Y, multiplier=1.5)
ll = np.nanmin(iqr)
ul = np.nanmax(iqr)
```

calc_oxygen then runs as expected.

**Comment by callumrollo** [comment]
This issue blocks further progress on #95

**Comment by callumrollo** [comment]
Despite three values being returned by calc_oxygen purporting to be oxygen concentration in mL/L, theoretical oxygen saturation percentage and apparent oxygen utilisation, all three are the same array.

The netcdf attributes are filled out, but the value for all three of these is the variable o2mll. How on earth did this get into production?

**Comment by callumrollo** [comment]
The variables o2aou and o2pct = are created lines 255-256 but never used

**Comment by jbusecke** [comment]
😱

**Comment by callumrollo** [comment]
Looked through the history, this has been b0rked since first committed last April. Oh dear

**Comment by callumrollo** [comment]
I'm gonna put a pin in further oxygen related improvements til we can sort this out. May be safer to start from scratch. Good luck @soerenthomsen!

**Comment by jbusecke** [comment]
I think that is reasonable @callumrollo. If there is momentum around a substantial refactor of the module, we should maybe just put a note in the README?

Any further development should start from the tests to avoid this scenario in the future @soerenthomsen.

**Comment by isgiddy** [comment]
I edited this code to make it function for my work a few months ago (but never pushed to the repository). But I think if there is a refactor going to happen, might as well just leave it?

**Comment by jbusecke** [comment]
@isgiddy Perhaps you can share your code over at https://github.com/GliderToolsCommunity/GliderTools/discussions/74? 

Just so any potential duplication of efforts is prevented?

**Comment by lukegre** [comment]
Just read through this thread 🤦🏻‍♂️ my bad. Glad you guys are on board now 😄 

But to answer this question...  

> The netcdf attributes are filled out, but the value for all three of these is the variable o2mll. How on earth did this get into production?

![](https://bluecanvas.io/images/git-memes/git-push-origin-master-f.jpg)

**Comment by tomhull** [comment]
Hey, so I'm finally finding some time to have a closer look at the oxygen processing building on what Callum has done and I'll hopefully code up the oxygen lag correction algorithms with the various optode quirks.

Few questions and comments about the code as it is.
Why are we using mL/L? it's not the unit the sensors report (umol / L) or what's recommended by the oxygen SCOR working group. http://cfconventions.org expects oxygen variables to be umol kg-1.

"theoretical oxygen saturation" is not the correct term, I'm not sure what the "theoretical" bit comes from unless it's because it's relative to the equilibrium saturation concentration (here called o2sat, but often called C* or Csat), but it's no more theoretical than the actual measurements. It's currently being calculated using `seawater` but it's using the Weiss1970 rather than the recommended Garcia&Gordon1990 equation. The Garcia equation is also the equation used internally by the sensor. `gsw` doesn't have either function, but I'm happy to implement it here and avoid calling `seawater`.

The conversions being done are missing a bit of accuracy , 
SCOR working group 142 https://archimer.ifremer.fr/doc/00348/45915/ has MATLAB code for all the conversions I'm happy to port over.

**Comment by tomhull** [comment]
actually, also is there any problem with spitting oxygen into a separate file?

**Comment by jbusecke** [comment]
I dont see one from an organization standpoint. Do you want to start a new module and we deprecate the existing functionality once that is in good shape?

**Comment by callumrollo** [comment]
Thanks for picking this up Tom, It's past my rudimentary oxygen expertise. If you could lose `seawater` in the new version that would be great. We could then close #99 and only depend on `gsw` for the physics stuff

**Comment by soerenthomsen** [comment]
@tomhull nice that you find time to work on this issue. Let me know if there is anything I can do to support you.
