### ISSUE TITLE
Plot shading flat is deprecated

### ISSUE THREAD

**Issue by callumrollo** [GliderToolsCommunity/GliderTools#115]
**Describe the bug**

**To Reproduce**
1. gt.plot(x, y, grid)
Where grid is a 2D array with dimensions x and y

**Expected behavior**
Not to cause a warning. Note that this warning will graduate to an error soon!

**Screenshots**
![image](https://user-images.githubusercontent.com/28703282/115910681-0657c680-a465-11eb-93e5-ce5597d4b5ac.png)

I'm pretty sure this could be fixed with the addition of `shading='auto'` as a default kwarg to pcolormesh:

![image](https://user-images.githubusercontent.com/28703282/115910780-2ab3a300-a465-11eb-99b0-f5c410424268.png)

Not 100 % sure on implementation of this though, as it's in the `plot_functions` class

**Comment by bastienqueste** [comment]
Note that using shading='auto' sometimes fails in the current release when other options affecting axis are passed to the function (eg. log scale axis). I'd recommend explicitly defining 'nearest' for a typical pcolor behaviour, or 'gouraud' for aesthetics, rather than relying on the rather vague 'auto'.

**Comment by jbusecke** [comment]
From reading this https://github.com/matplotlib/matplotlib/pull/16258, it seems like @dhruvbalwada s suggestion to set shading to `auto` is the right call. (or `nearest` if we know that our input data will always be the same shape as coordinates. Do we thought?)

I think inserting `kwargs.setdefault('shading', 'auto)` [here](https://github.com/GliderToolsCommunity/GliderTools/blob/01092e381983b5360a7bb7ee399927deedad5657/glidertools/plot.py#L136) should  do the trick.

**Comment by jbusecke** [comment]
Side note, we could also absorb the `rasterized=True` argument from below in this manner. The advantage of doing it this way is that the user could manually override this. 

Currently `gt.plot(x, y, grid, rasterize=False)` should produce an error.

**Comment by dhruvbalwada** [comment]
Since this plotting function is used during QC, I wonder if `garaud` would create problems there? Maybe someone having done more QC would know. 

Also this function grids the data in depth/pressure before plotting it, so I doubt there would ever be a situation where the input data will not the be same shape - the input data to the plotting function is being created inside the call.

**Comment by bastienqueste** [comment]
Then suggest slight alteration of @jbusecke's suggestion of "inserting `kwargs.setdefault('shading', 'nearest')` [here](https://github.com/GliderToolsCommunity/GliderTools/blob/01092e381983b5360a7bb7ee399927deedad5657/glidertools/plot.py#L136) should do the trick."

**Comment by jbusecke** [comment]
Who wants to do the PR then, hehe.

**Comment by dhruvbalwada** [comment]
I'll do this in a bit.
