### ISSUE TITLE
Missing variable error in physics.mld_profile

### ISSUE THREAD

**Issue by smwoodman** [GliderToolsCommunity/GliderTools#188]
In the function physics.mld_profile, in the `if len(df) == 0:` block, there is no 'message' variable defined. Thus, if the code hits this block, the `warnings.warn(message, category=GliderToolsWarning)` line will throw the error "UnboundLocalError: cannot access local variable 'message' where it is not associated with a value".

Happy to provide more info if useful.

**Comment by MartinMohrmann** [comment]
Thank you so much for documenting this bug! 
I created a PR (#190) that will be merged soon. 
Since you did half the work with your excellent analysis of the bug, I encourage you to start working with us on GliderTools anytime (and become a co-authour in the process). Here is how to get started in case you are inerested: https://glidertools.readthedocs.io/en/latest/contributing.html
