### ISSUE TITLE
Documentation theme broken

### ISSUE THREAD

**Issue by MartinMohrmann** [GliderToolsCommunity/GliderTools#200]
The theme of the readthedocs documentation is broken. 
You can see this by comparing 
https://glidertools.readthedocs.io/en/stable/
with 
https://glidertools.readthedocs.io/en/latest/
In its current state, the documentation is functional, but ugly. To me it looks like a theme become unavailable or some css missing. I assume I broke it myself with Pull Request #197 (sorry!). However, the documentation was not building at all before #197, so a simple downgrade is probably not a good option.  
![Screenshot from 2024-04-19 10-58-11](https://github.com/GliderToolsCommunity/GliderTools/assets/37417617/6538ba0d-2014-45d8-9f4b-1beb974201db)

**Comment by callumrollo** [comment]
hmmm. I've had a look through the docs build logs and can't find an obvious source for the error. All the warnings relate to the two functions that didn't have the right name in the API (PR #199). Could be worth merging that PR and see if that fixes the build?

I guess otherwise there must be some upstream changes in theming that have broken it

**Comment by MartinMohrmann** [comment]
Closing this, I repaired the documentation building and theming in #203. Some outdated css was removed during the process, but the result looks good and the difference is hardly visible.
