### ISSUE TITLE
Create requirements files

### ISSUE THREAD

**Issue by callumrollo** [GliderToolsCommunity/GliderTools#98]
Is there a reason these don't exist? There's a list of requirements in `setup.cfg` but this does not include all the packages we need, e.g **pandas** is imported in physics/mixed_layer_depth but does not appear in the list

**Comment by jbusecke** [comment]
Thanks for bringing this up. 

> Is there a reason these don't exist?

I think (but might be wrong) that we don't explicitly need this. I personally do not like to have dependencies in many different files, as they tend to get out of sync. The new CI implemented in #54 relies on the conda environment files in `ci/...`, so pandas should be added there.

More generally, this really highlights the urgent need for some basic testing! 
Basically my changes break the installation, but I was not able to detect them, because there is not even a single test calling that module!!! 

We should fix this asap! Happy to put in a PR.

**Comment by callumrollo** [comment]
Yeah we should at the very least be running every function on some synthetic data, just to trigger environment errors. Maybe we could use the sample data in tests/data? I expect we could make a solid start by just copying from the demo notebook

**Comment by jbusecke** [comment]
I did something even more basic. I just import all function in each module and run some dummy test in #102. That should at least expose dependency problems. After that is merged any kind of 'actual' test coverage would be good.

**Comment by jbusecke** [comment]
I also homogenized the requirements in `setup.cfg`.
